name = "SententialDecisionDiagrams"
uuid = "7fb4d062-ec23-11e9-0b7c-0d74514dd3ea"
authors = ["pedrozudo <pedro.zuidbergdosmartires@cs.kuleuven.be>"]
version = "0.1.2"


[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12.0"
julia = "1"
